server:
  port: '8082'
  error:
    include-message: always

spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  datasource:
    url: 'jdbc:mysql://localhost:3306/department'
    username: root
    password: mrbui123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
welcome:
  message: Welcome to the server!

---

spring:
  profiles: qa
  datasource:
    url: 'jdbc:mysql://localhost:3306/department-qa'
    username: root
    password: mrbui123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
welcome:
  message: Welcome to the server!

---

spring:
  profiles: prod
  datasource:
    url: 'jdbc:mysql://localhost:3306/department-prod'
    username: root
    password: mrbui123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
welcome:
  message: Welcome to the server!
